kind = "web"
previewPath = "/"
title = "DohaHappyEndings"
version = "1.0.0"
id = "artifacts/dohahappyendings"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25021

[services.development]
run = "pnpm --filter @workspace/dohahappyendings run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/dohahappyendings", "run", "build" ]
run = "pnpm --filter @workspace/dohahappyendings run start"

[services.env]
PORT = "25021"
